# rpxy Reverse Proxy Configuration for Railway
# Uses environment variables for flexible deployment

# Server listen configuration
listen_port = $PORT
listen_port_tls = $TLS_PORT

# IPv6 support required for Railway
listen_ipv6 = true
listen_ipv6_only = true

# Global performance settings
worker_threads = $WORKER_THREADS
max_clients = $MAX_CLIENTS
tcp_listen_backlog = $TCP_LISTEN_BACKLOG

# Logging configuration
log_level = "$LOG_LEVEL"
log_to_file = false

# Health check endpoint
[health_check]
path = "$HEALTH_CHECK_PATH"

# Default application routing
[apps.default]
server_name = "$SERVER_NAME"
default_app = true

[[apps.default.reverse_proxy]]
upstream = [
    { location = "$UPSTREAM_URL" }
]
load_balance = "$LOAD_BALANCE"
health_check_uri = "$UPSTREAM_HEALTH_CHECK"
health_check_timeout_sec = $HEALTH_CHECK_TIMEOUT

# Optional: Path-based routing for API endpoints
[[apps.default.reverse_proxy]]
path = "$API_PATH"
upstream = [
    { location = "$API_UPSTREAM_URL" }
]
load_balance = "$API_LOAD_BALANCE"

# Optional: Custom domain routing (only if CUSTOM_SERVER_NAME is set)
# Uncomment and configure if needed:
# [apps.custom]
# server_name = "${CUSTOM_SERVER_NAME}"
# default_app = false
# 
# [[apps.custom.reverse_proxy]]
# upstream = [
#     { location = "${CUSTOM_UPSTREAM_URL}" }
# ]
# load_balance = "${CUSTOM_LOAD_BALANCE:-round_robin}"

# TLS Configuration (only if cert paths are provided)
# Uncomment and configure if needed:
# [tls]
# tls_cert_path = "${TLS_CERT_PATH}"
# tls_cert_key_path = "${TLS_KEY_PATH}"

# Experimental features
[experimental]
h3 = $ENABLE_HTTP3

# ACME/Let's Encrypt configuration (only if email is provided)
# Uncomment and configure if needed:
# [experimental.acme]
# dir_url = "${ACME_DIR_URL:-https://acme-v02.api.letsencrypt.org/directory}"
# email = "${ACME_EMAIL}"
# staging = "${ACME_STAGING:-false}"